services:
  app_service:
    network_mode: host
    build:
      network: host
      context: .
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    # user: "1000:1000"
    working_dir: /app
    volumes:
      - ./:/app

    tty: true
    command: bash