services:
  app_service:
    network_mode: host
    build:
      network: host
      context: .
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
        DIR: "${DIR}"
    working_dir: /${DIR}
    volumes:
      - ./:/${DIR}

    tty: true
    command: bash