services:
  cppdev:
    network_mode: host
    build:
      network: host
      context: .
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    working_dir: /cppdev
    volumes:
      - ./:/cppdev

    tty: true
    command: bash