FROM ubuntu:24.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    tzdata \
    build-essential \
    curl \
    git \
    cmake \
    clang \
    libssl-dev \
    vim \
    wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# ## ホストのUID/GIDでユーザー作成
ARG UID
ARG GID
RUN groupadd -g ${GID} appgroup && \
    useradd -m -u ${UID} -g ${GID} -s /bin/bash appuser

## 任意のディレクトリパス + 作業ディレクトリの所有者を設定
ARG DIR
WORKDIR /${DIR}

COPY . .

# # 非rootユーザで実行
RUN chown -R appuser:appgroup /${DIR}
USER appuser

CMD ["bash"]